### ISSUE TITLE
[DMP 2024]: Developing Math Games for Sugar Labs

### ISSUE THREAD

**Issue by SumitMakariye** [sugarlabs/DMP#16]
## Description
This project aims to enrich the Sugar environment with 6 to 8 new math games and puzzles inspired by Bogomolny's ideas and the vast resources available at "cut-the-knot.org." The addition of these games will enhance the educational value of Sugar, providing children aged 6 to 12 with engaging activities to reinforce math concepts.

## Goals
- [ ] [Goal 1] Develop Lewis Carroll's Game of Logic.
- [ ] [Goal 2] Implement Pascal's Triangle game.
- [ ] [Goal 3] Create a Nim game variant.
- [ ] [Goal 4] Introduce The Candy Game.
- [ ] [Goals Achieved By Mid-point Milestone]  1-4 by the mid-point milestone

### Setup/Installation

The games will need to run in the Sugar environment and be coded in Python using GTK3 and the Sugar Toolkit. The pygame/sugargame module will be a useful resource as well.

To set up the Sugar environment, please refer to these [docs](https://github.com/sugarlabs/sugar-docs).

### Expected Outcome

The final product should consist of 6 to 8 standalone Sugar activities, each offering an interactive and educational math experience. These games should adhere to Sugar HI guidelines and be packaged for Flatpak.

### Acceptance Criteria

Each game must function as a standalone Sugar activity.
Games should be appropriate and engaging for children aged 6 to 12.
Adherence to Sugar HI guidelines.
Individual packaging for Flatpak.

### Implementation Details

Technologies: Python3, sugar-toolkit-gtk3, sugargames.
Mockups/Wireframes

### Product Name

Math Games

### Organisation Name

Sugar Labs

### Domain

⁠Education

### Tech Skills Needed

Python

### Mentor(s)

@chimosky, @walterbender

### Category

Frontend

**Comment by kshitijdshah99** [comment]
@walterbender can we have this issue closed?
@SumitMakariye there is already one issue open for Sugar games, pls check it.

**Comment by walterbender** [comment]
I didn't understand why this issue was created and had meant to ask.
